name: Run wasi-sdk
description: Build Webassembly using wasi-sdk
author: Zihuo Ng

inputs:
  args:
    description: Arguments to wasi-sdk's clang
    required: true
    default: --help

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
